name:                wl-bot
version:             0.0.0.1
github:              "nutr1t07/wl-bot"
license:             WTFPL
author:              "Nutr1t07"
maintainer:          "nutr1t07@outlook.com"
copyright:           "2019-2020 Nutr1t07"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         This is a program used to provide tools for QQ and Telegram groups.

dependencies:
- base >= 4.7 && < 5
- aeson
- text
- http-types
- bytestring
- wai-extra
- time
- scotty
- uri-encode
- stringsearch
- utf8-string
- random
- transformers
- wreq
- lens
- attoparsec
- directory
- websockets
- network

library:
  source-dirs: src

executables:
  wl-bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wl-bot

tests:
  wl-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wl-bot
